import {grayFromRgba,approximateLightBackground,profile,normaliseRoi,autoDividers,imageJPeakAreas,imageJPlotDimensions} from './gel/analysis.js';
import {rotateGray8} from './image/rotate.js';
const $=id=>document.getElementById(id), imageCanvas=$('imageCanvas'), plotCanvas=$('plotCanvas'), ictx=imageCanvas.getContext('2d'), pctx=plotCanvas.getContext('2d');
const state={raw:null,processed:null,w:0,h:0,roi:null,view:'original',drag:null,profile:null,dividers:null,centers:null,loadId:0,fileName:'',sourceRaw:null,sourceW:0,sourceH:0,rotation:0};
const backgroundWorker=new Worker(new URL('./background-worker.js',import.meta.url),{type:'module'});
backgroundWorker.onmessage=({data})=>{if(data.id!==state.loadId)return;if(data.error){$('imageMeta').textContent=`原图已显示；背景校正失败：${data.error}`;return;}state.processed=new Uint8ClampedArray(data.pixels);$('imageMeta').textContent=$('imageMeta').dataset.base+' · 背景校正完成';if(state.view==='processed')drawImage();};
backgroundWorker.onerror=()=>{$('imageMeta').textContent='原图已显示；背景校正 Worker 无法启动。请通过本地服务器打开网页。';};
function fitCanvas(c,w,h,maxH=560){const cssW=c.clientWidth||800,scale=Math.min(cssW/w,maxH/h,1);c.width=Math.round(w*scale);c.height=Math.round(h*scale);return scale;}
function drawImage(){if(!state.raw)return;const scale=fitCanvas(imageCanvas,state.w,state.h);const pix=state.view==='original'||!state.processed?state.raw:state.processed;const id=ictx.createImageData(state.w,state.h);for(let i=0;i<pix.length;i++){id.data[i*4]=id.data[i*4+1]=id.data[i*4+2]=pix[i];id.data[i*4+3]=255;}const off=document.createElement('canvas');off.width=state.w;off.height=state.h;off.getContext('2d').putImageData(id,0,0);ictx.drawImage(off,0,0,imageCanvas.width,imageCanvas.height);if(state.roi){const r=state.roi;ictx.strokeStyle='#f8ad32';ictx.lineWidth=1;ictx.strokeRect(Math.round(r.x*scale)+.5,Math.round(r.y*scale)+.5,Math.round(r.w*scale),Math.round(r.h*scale));ictx.fillStyle='#f8ad32';for(const [x,y] of [[r.x,r.y],[r.x+r.w,r.y],[r.x+r.w,r.y+r.h],[r.x,r.y+r.h]]){ictx.beginPath();ictx.arc(x*scale,y*scale,3,0,Math.PI*2);ictx.fill();}}}
function analyze(){if(!state.raw||!state.roi)return alert('请先上传图片并框选横向 ROI。');const mode=$('backgroundMode').value;if(mode==='subtract'&&!state.processed)return alert('背景校正仍在进行，请在文件名位置显示“背景校正完成”后再分析。');const n=Number($('laneCount').value);if(!Number.isInteger(n)||n<1)return alert('请输入有效泳道数量。');state.roi=normaliseRoi(state.roi,state.w,state.h);state.profile=profile(mode==='subtract'?state.processed:state.raw,state.w,state.roi);const a=autoDividers(state.profile,n);state.dividers=a.dividers;state.centers=a.centers;drawPlot();renderResults();}
function plotDims(){return {w:plotCanvas.width,h:plotCanvas.height,pad:34,base:plotCanvas.height-28,top:18};}
function drawPlot(){const c=plotCanvas,p=state.profile;if(!p){c.width=Math.max(500,c.clientWidth||500);c.height=330;pctx.clearRect(0,0,c.width,c.height);return;}c.width=Math.max(500,c.clientWidth||500);c.height=330;const d=plotDims(),min=Math.min(...p),max=Math.max(...p),ys=max===min?1:(d.base-d.top)/(max-min),xs=(d.w-d.pad*2)/(p.length-1);pctx.clearRect(0,0,d.w,d.h);pctx.strokeStyle='#77838e';pctx.beginPath();pctx.moveTo(d.pad,d.base);pctx.lineTo(d.w-d.pad,d.base);pctx.stroke();pctx.strokeStyle='#174e6a';pctx.lineWidth=2;pctx.beginPath();p.forEach((v,i)=>{const x=d.pad+i*xs,y=d.base-(v-min)*ys;i?pctx.lineTo(x,y):pctx.moveTo(x,y)});pctx.stroke();state.dividers.forEach((v,i)=>{const x=d.pad+v*xs;pctx.strokeStyle=i===0||i===state.dividers.length-1?'#b7c0c8':'#e98127';pctx.lineWidth=2;pctx.beginPath();pctx.moveTo(x,d.base);pctx.lineTo(x,d.top);pctx.stroke()});state.centers.forEach((v,i)=>{pctx.fillStyle='#174e6a';pctx.fillRect(d.pad+v*xs-2,d.base+7,4,7);pctx.fillText(`L${i+1}`,d.pad+v*xs-8,d.h-7)});const q=imageJPlotDimensions(p.length);$('plotStatus').textContent=`ROI x=${state.roi.x}, y=${state.roi.y}, ${state.roi.w} × ${state.roi.h}px · 定量网格 ${q.plotWidth} × ${q.plotHeight}px · ${state.centers.length} lanes`;}
function resultData(){if(!state.profile)return[];return imageJPeakAreas(state.profile,state.dividers);}
function renderResults(){const rs=resultData(),tbody=$('resultsBody');tbody.innerHTML=rs.map((r,i)=>`<tr><td>${i+1}</td><td>${r.area.toFixed(3)}</td><td>${r.signal.toFixed(1)}</td></tr>`).join('');}
function setImageFromRgba(rgba,width,height,file){state.w=width;state.h=height;state.fileName=file.name||'clipboard-image';state.raw=grayFromRgba(rgba);state.sourceRaw=state.raw.slice();state.sourceW=width;state.sourceH=height;state.rotation=0;$('angleInput').value='0';state.processed=null;state.roi={x:Math.round(state.w*.08),y:Math.round(state.h*.35),w:Math.round(state.w*.84),h:Math.max(12,Math.round(state.h*.3))};state.loadId++;const base=`${state.fileName} · ${state.w} × ${state.h}px`;$('imageMeta').dataset.base=base;$('imageMeta').textContent=base+' · 正在背景校正…';drawImage();const workerPixels=state.raw.slice();backgroundWorker.postMessage({id:state.loadId,width:state.w,height:state.h,pixels:workerPixels.buffer},[workerPixels.buffer]);}
function loadTiffFile(file){$('imageMeta').textContent='正在本地解码 TIFF…';const reader=new FileReader();reader.onload=()=>requestAnimationFrame(()=>{try{const ifd=window.UTIF.decode(reader.result)[0];if(!ifd)throw new Error('未找到图像页');window.UTIF.decodeImage(reader.result,ifd);setImageFromRgba(window.UTIF.toRGBA8(ifd),ifd.width,ifd.height,file);}catch(err){console.error(err);$('imageMeta').textContent='读取 TIFF 失败：该 TIFF 编码暂不受支持或文件已损坏。';}});reader.onerror=()=>{$('imageMeta').textContent='读取 TIFF 失败：无法读取本地文件。';};reader.readAsArrayBuffer(file);}
function loadImageFile(file){if(!file)return;const isTiff=/\.(tif|tiff)$/i.test(file.name)||/tiff/i.test(file.type);if(isTiff){loadTiffFile(file);return;}if(!file.type.startsWith('image/')){$('imageMeta').textContent='读取失败：请拖入或选择 PNG、JPG、WebP、BMP、GIF 或 TIFF 图片。';return;}$('imageMeta').textContent='正在读取原图…';const img=new Image();img.onload=()=>requestAnimationFrame(()=>{try{const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0);setImageFromRgba(x.getImageData(0,0,c.width,c.height).data,c.width,c.height,file);}catch(err){console.error(err);$('imageMeta').textContent='读取失败：浏览器无法处理该图片。请使用 PNG、JPG 或 TIFF。';}});img.onerror=()=>{$('imageMeta').textContent='读取失败：当前浏览器不支持该文件格式。请使用 PNG、JPG 或 TIFF。';};img.src=URL.createObjectURL(file);}
$('fileInput').addEventListener('change',e=>{loadImageFile(e.target.files[0]);e.target.value='';});
['dragenter','dragover'].forEach(type=>imageCanvas.addEventListener(type,e=>{e.preventDefault();imageCanvas.classList.add('drag-active');}));['dragleave','drop'].forEach(type=>imageCanvas.addEventListener(type,e=>{e.preventDefault();imageCanvas.classList.remove('drag-active');}));imageCanvas.addEventListener('drop',e=>loadImageFile(e.dataTransfer.files[0]));
document.addEventListener('paste',e=>{const item=[...(e.clipboardData?.items||[])].find(x=>x.kind==='file'&&x.type.startsWith('image/'));if(!item)return;const file=item.getAsFile();if(file){e.preventDefault();loadImageFile(file);}});
['originalBtn','processedBtn'].forEach(id=>$(id).addEventListener('click',()=>{state.view=id==='originalBtn'?'original':'processed';$('originalBtn').classList.toggle('active',state.view==='original');$('processedBtn').classList.toggle('active',state.view==='processed');drawImage()}));
function applyRotation(){if(!state.sourceRaw)return alert('请先上传图片。');const angle=Number($('angleInput').value);if(!Number.isFinite(angle)||angle<-180||angle>180)return alert('请输入 -180° 到 180° 之间的有效角度。');const rotated=rotateGray8(state.sourceRaw,state.sourceW,state.sourceH,angle);state.raw=rotated.pixels;state.w=rotated.width;state.h=rotated.height;state.rotation=angle;state.processed=null;state.roi=null;state.profile=null;state.dividers=null;state.centers=null;state.loadId++;const base=`${state.fileName} · ${state.w} × ${state.h}px · 旋转 ${angle}°`;$('imageMeta').dataset.base=base;$('imageMeta').textContent=base+' · 正在背景校正…';drawImage();drawPlot();$('plotStatus').textContent='图像已旋转，请重新框选 ROI 并分析';$('resultsBody').innerHTML='<tr><td colspan="3">旋转后请重新框选并分析</td></tr>';const workerPixels=state.raw.slice();backgroundWorker.postMessage({id:state.loadId,width:state.w,height:state.h,pixels:workerPixels.buffer},[workerPixels.buffer]);}
$('rotateBtn').addEventListener('click',applyRotation);$('angleInput').addEventListener('keydown',e=>{if(e.key==='Enter')applyRotation();});
function imagePoint(e){const r=imageCanvas.getBoundingClientRect();return{x:(e.clientX-r.left)*state.w/r.width,y:(e.clientY-r.top)*state.h/r.height};}function roiHandleAt(p,r){const scale=imageCanvas.width/state.w,hit=12/scale;for(const [name,x,y] of [['nw',r.x,r.y],['ne',r.x+r.w,r.y],['se',r.x+r.w,r.y+r.h],['sw',r.x,r.y+r.h]])if(Math.hypot(p.x-x,p.y-y)<=hit)return name;return null;}imageCanvas.addEventListener('pointerdown',e=>{if(!state.raw)return;const p=imagePoint(e),r=state.roi,handle=r&&roiHandleAt(p,r);state.drag=handle?{type:'resize',handle,start:p,roi:{...r}}:{type:'new',start:p};imageCanvas.setPointerCapture(e.pointerId)});imageCanvas.addEventListener('pointermove',e=>{const p=imagePoint(e),d=state.drag;if(!d){const h=state.roi&&roiHandleAt(p,state.roi);imageCanvas.style.cursor=h?'nwse-resize':'crosshair';return;}if(d.type==='new')state.roi={x:Math.min(d.start.x,p.x),y:Math.min(d.start.y,p.y),w:Math.abs(p.x-d.start.x),h:Math.abs(p.y-d.start.y)};if(d.type==='resize'){let left=d.roi.x,top=d.roi.y,right=d.roi.x+d.roi.w,bottom=d.roi.y+d.roi.h;if(d.handle.includes('w'))left=Math.max(0,Math.min(right-2,p.x));if(d.handle.includes('e'))right=Math.min(state.w,Math.max(left+2,p.x));if(d.handle.includes('n'))top=Math.max(0,Math.min(bottom-2,p.y));if(d.handle.includes('s'))bottom=Math.min(state.h,Math.max(top+2,p.y));state.roi={x:left,y:top,w:right-left,h:bottom-top};}drawImage()});imageCanvas.addEventListener('pointerup',()=>{state.drag=null;imageCanvas.style.cursor='crosshair'});
$('analyzeBtn').addEventListener('click',analyze);plotCanvas.addEventListener('pointerdown',e=>{if(!state.dividers)return;const r=plotCanvas.getBoundingClientRect(),x=(e.clientX-r.left)*plotCanvas.width/r.width,d=plotDims(),idx=state.dividers.slice(1,-1).findIndex(v=>Math.abs(d.pad+v*(d.w-d.pad*2)/(state.profile.length-1)-x)<12);if(idx>=0)state.drag={type:'divider',idx:idx+1};});plotCanvas.addEventListener('pointermove',e=>{if(!state.drag||state.drag.type!=='divider')return;const r=plotCanvas.getBoundingClientRect(),x=(e.clientX-r.left)*plotCanvas.width/r.width,d=plotDims(),i=state.drag.idx,v=Math.round((x-d.pad)*(state.profile.length-1)/(d.w-d.pad*2));state.dividers[i]=Math.max(state.dividers[i-1]+1,Math.min(state.dividers[i+1]-1,v));drawPlot();renderResults()});plotCanvas.addEventListener('pointerup',()=>state.drag=null);
function values(){return resultData().map(x=>x.area.toFixed(3)).join('\n')}function copy(t){navigator.clipboard.writeText(t).then(()=>alert('已复制。'))}$('copyValuesBtn').onclick=()=>copy(values());$('copyTableBtn').onclick=()=>copy('Lane\tArea\n'+resultData().map((x,i)=>`${i+1}\t${x.area.toFixed(3)}`).join('\n'));$('csvBtn').onclick=()=>{const b=new Blob(['Lane,Area\n'+resultData().map((x,i)=>`${i+1},${x.area.toFixed(3)}`).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='wb-peak-area.csv';a.click();};window.addEventListener('resize',()=>{drawImage();drawPlot()});drawPlot();
